app:
  name: srv-1
  group: frontend
  container:
    image: aimvector/nodejs:v1
    port: 5000
    imagePullPolicy: Always
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
      limits:
        memory: "256Mi"
        cpu: "500m"
