repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: svc-1
    chart: ./charts/app
    values:
      - ./values/service.yaml
  - name: svc-2
    chart: ./charts/app
    values:
      - ./values/service2.yaml

  - name: ingress-backend
    chart: stable/nginx-ingress
    version: 1.36.0

  - name: ingress-controller
    chart: ./charts/ingress
    values:
      - ./values/ingress.yaml
